# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Keir Little
email: website@keirlittle.com
description: > # this means to ignore newlines until "baseurl:"
  Keir Little is an aspiring scientist, currently studying for an MRes at
  University College London.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.keirlittle.com" # the base hostname & protocol for your site
twitter_username: keirwl
github_username:  keirwl

# Build settings
markdown: kramdown
